changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - ecp88
  categories:
    - title: "\U0001F389 New Features"
      labels:
        - feature
    - title: "\U0001F528 Dependencies"
      labels:
        - dependency
    - title: "\U0001F6E0 Breaking Changes"
      labels:
        - breaking-change
    - title: "\U0001F41B Fixes"
      labels:
        - bug
    - title: "\U0001F31F Enhancements"
      labels:
        - enhancement
