changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - ecp88
  categories:
    - title: "\U0001F389 New Features"
      labels:
        - feature
    - title: "Dependencies \U0001F528"
      labels:
        - dependency
    - title: "Breaking Changes \U0001F6E0"
      labels:
        - breaking-change
    - title: "\U0001F41B Fixes"
      labels:
        - bug
    - title: "Enhancements \U0001F31F"
      labels:
        - enhancement
