function generateSiteMap() {
  //this fn serves to build a sitemap with the env specific hostname
  return `
    <?xml version="1.0" encoding="UTF-8"?>
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
    xmlns:xhtml="http://www.w3.org/1999/xhtml"
    xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
    xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-announces-the-blockchain-operating-system</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/inscribe.near/widget/NEAT</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/welcome-to-near-the-b-o-s</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/horizon</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/signin</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/signup</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/nearcon23.near/widget/Index</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/embracing-decentralization-whats-next-for-the-near-wallet</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/inscribe.near/widget/NRC-20</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/near/widget/Search.IndexPage</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/papers/the-official-near-white-paper</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/near/widget/ProfilePage</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/ecosystem</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/near/widget/NearOrg.HomePage</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/applications</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/near/widget/ComponentDetailsPage</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/bridge</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/astraplusplus.ndctools.near/widget/home</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/devgovgigs.near/widget/app</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/election.ndctools.near/widget/NDC.Elections.Main</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/getting-started-with-the-near-wallet</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/learn</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-token-supply-and-distribution</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-launches-near-da-to-offer-secure-cost-effective-data-availability-for-eth-rollups-and-ethereum-developers</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/about</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/staking-rewards-are-live</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/data-availability</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/memelol.near/widget/lol.App</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/ecosystem/get-funding</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/nearhorizon.near/widget/Index</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/arbitrum-integrates-near-da-for-developers-building-ethereum-rollups</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/self-sovereignty-is-near-a-vision-for-our-ecosystem</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/meta-pool-official.near/widget/ImprovementProposals</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/about/network/validators</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/metamask-snaps</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/devgovgigs.near/widget/gigs-board.pages.Feed</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/papers/nightshade</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/sandbox</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/sweat-economy-launches-in-the-usa-opening-the-door-to-millions-of-new-web3-users</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/sweatcoin-partners-with-near-foundation-to-create-a-new-movement-economy</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/events</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/nomination.ndctools.near/widget/NDC.Nomination.Page</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-wallet-rockets-to-over-20-million-users-with-sweat-partnership</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/brand</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/humans-of-near.near/widget/humans.nearverselabs.com</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/a-reminder-to-migrate-from-near-wallet</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blockchain</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-protocol-economics</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/international-cricket-council-and-near-foundation-sign-multiyear-partnership-to-boost-global-fan-engagement-through-web3</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/enter-the-black-dragon-near-co-founder-joins-the-near-foundation-as-ceo</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/cosmose-ai-harnesses-the-open-web-and-near-with-kaikainow</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/easypoll-v0.ndc-widgets.near/widget/EasyPoll</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/ecosystem/work-and-earn</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/what-the-near-foundation-does</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/announcing-web-push-notifications-on-b-o-s</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/2023-near-in-review</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/send-near-to-anyone-with-near-drops</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-protocol-roadmap-2023-4-the-next-2-years-of-near%EF%BF%BC</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/memiko.near/widget/mem.App</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/the-continued-evolution-of-the-near-foundation</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-q4-protocol-roadmap-update</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nearcon-23-day-three-governance-and-multi-chain-in-the-spotlight</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/devhub.near/widget/app</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/ai-is-near-the-future-of-ai-on-the-open-web-at-nearcon-23</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/nearweekapp.near/widget/nearweek.com</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-da-integrates-with-polygon-cdk-for-developers-building-ethereum-zk-rollups</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/usdc-launches-natively-on-the-near-protocol</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/devgovgigs.near/widget/gigs-board.pages.Post</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/announcing-the-launch-of-pagoda-the-worlds-first-web3-startup-platform</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nearcon-the-ultimate-web3-education-for-only-99</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/an-update-from-the-near-foundation</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/onboarding</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/near/widget/ActivityPage</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/settings</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/ecosystem/community</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/introducing-wallet-selector-a-new-tool-for-the-near-ecosystem</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-q2-protocol-roadmap-update</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/interactive-polygon-zkevm-app-dashboard-launches-on-the-near-blockchain-operating-system</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-tasks-launches-ai-marketplace-on-near-to-revolutionize-the-future-of-work</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/gateways</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/components</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/an-update-on-the-ndc-funding-and-support-for-grassroots-projects</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/phase-2-of-near-sharding-launches</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-climate-neutral-product</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-wallet-update-staking-and-withdrawing-tokens</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/mintbase.near/widget/nft-marketplace</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-protocol-partners-with-d3-to-apply-for-near-top-level-domain</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/why-chain-abstraction-is-the-next-frontier-for-web3</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/ndcdev.near/widget/MDAO.App</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-transparency-report-q2-2023</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/open-web-applications</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/privacy</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/tag/partnerships</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/people</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/about/network</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/eth-near-rainbow-bridge</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/cosmose-and-near-foundation-set-to-revolutionize-retail-with-web3-and-ai</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/aurora-launches-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/an-update-on-near-ecosystem-block-explorers</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/illia-polosukhin-returns-to-near-foundation-council-to-continue-evolution-of-near-ecosystem-diogo-monica-founder-of-anchorage-joins-as-chairman</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/how-glass-is-uncorking-adult-beverage-loyalty-with-web3-and-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/introducing-the-near-foundation</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/introducing-ncon-and-how-to-use-it-at-nearcon-23</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-teams-with-google-cloud-to-accelerate-web3-startups</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/hackbox.near/widget/home</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/near/widget/AppLibrary.IndexPage</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-ai-near-protocol</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/papers/economics-in-sharded-blockchain</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-web-wallet-security-update</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/check-out-the-pagoda-product-roadmap</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/devgovgigs.near/widget/devhub.entity.addon.blog.Configurator</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/dataplatform.near/widget/QueryApi.App</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-announces-800-million-in-funding-initiatives-to-support-ecosystem-growth</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/blockchain-scaling-approaches-near-sharding-vs-layer-2s</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/the-beginners-guide-to-the-near-blockchain</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/doomslug-comparison</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/fastauth-sdk-beta-now-available</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-launches-usn-protection-programme-aurora</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/why-near-data-availability</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-wallet-will-remain-online-until-the-end-of-the-year</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/meta-pool-launches-enterprise-node-operators-program</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/coin98-launches-decentralized-dapp-store-for-its-7-million-users-on-nears-blockchain-operating-system-b-o-s</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/metabuild</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/icc-launches-captains-call-game-on-near-to-level-up-cricket-fandom-during-world-cup</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-launches-nightshade-sharding-paving-the-way-for-mass-adoption</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/introducing-nearpay-the-first-bridge-to-fiat-debit-card-on-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/cookies</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-announces-the-blockchain-operation-system</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/defi</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/nearcatalog.near/widget/Index</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/sking.near/widget/DAO.Page</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/nearweekapp.near/widget/nearweek-news</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/get-ready-to-sweat-learn-and-earn-with-the-most-active-near-dapp</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-launches-simple-nightshade-the-first-step-towards-a-sharded-blockchain</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/randomness-threshold-signatures</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/what-is-the-near-digital-collective</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/achildhoodhero.near/widget/nearweek.editorial.bos</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/statement-in-full-near-foundation-to-fund-usn-protection-programme</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nearcon-irl-hackathon-2023-build-the-open-web</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/use-cases</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/proofofvibes.near/widget/Vibes.DAO.main</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-transparency-report-q1-2023</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/devgovgigs.near/widget/Ideas</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/williamxx.near/widget/creatives.dao.web</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/nearukraineguild.near/widget/NDC.Elections.Main</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/pyth-price-feeds-launch-on-near-protocol-bringing-equity-commodities-and-market-data-on-chain</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/thresholded-proof-of-stake</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/the-near-blockchain-is-climate-neutral</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/zavodil.near/widget/StakingPools</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/layer-2</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/fast-auth-and-relayers</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/berklee-college-of-music-partners-with-near-foundation-to-build-music-licensing-platform</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-protocol-bigquery-public-dataset</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/how-solaire-is-revolutionizing-the-fashion-industry-with-web3-technology-and-building-the-retail-infrastructure-on-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/about/contact-us</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nearcon-2022-highlights-talks-and-videos</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundations-response-to-the-coinbase-sec-filing</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/get-ready-for-redacted-at-nearcon-23</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/the-rainbow-bridge-is-live</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/ai-is-near-illia-polosukhin-on-ai-and-the-open-web-at-nearcon-23</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/case-studies/kurtosis</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/near/widget/ComponentsPage</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/denysk.near/widget/NearStats</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-releases-javascript-sdk-bringing-web3-to-20-million-developers</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/about/brand</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/los-angeles-football-club-and-dropt-rewrite-fan-experience-playbook-utilizing-near-protocol</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/education</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-decentralization-aurora-evm</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/learn/learn-more</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-transparency-report</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-da-i</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-digital-collective-legal-framework</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/kudos.ndctools.near/widget/NDC.Kudos.Main</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/near/widget/AppLibrary.Nearcon.IndexPage</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/linearprotocol.near/widget/LiNEAR</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/genadrop.near/widget/CafeCartel.Index</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-gaming-the-future-of-gaming-on-web3</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-strategic-update-and-outlook-for-2023</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/use-cases/nft</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-unlocks-web3-b2b-solutions-with-sk-inc-cc-strategic-partnership</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-integrates-wormhole-to-launch-zk-enabled-cross-chain-communication-with-ethereum</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-mainnet-genesis</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/meet-the-2023-nearcon-irl-hackathon-winners</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/balancers-defi-protocol-is-bringing-programmable-liquidity-to-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/ndcplug.near/widget/NDC.SBT.main</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/welcome-to-nearcon-23-step-into-the-open-web</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/open-call-for-near-accelerator-partners</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-opens-the-door-to-more-wallets</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/grassroots-support-closing-update</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/built-on-near-celebrating-partners-and-innovators-at-nearcon-23</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-and-circle-announce-usdc-support-for-multi-chain-ecosystem</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/case-study-building-on-the-near-blockchain-operating-system-bos</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/data-infrastructure</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-pagoda-goals-and-target-metrics-for-2023</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nearcon-2023-get-tickets-get-involved-join-the-hackathon</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nearcon-23-unwrapped-lisbon-steps-into-the-open-web-in-iconic-fashion</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/ndc-v1-governance-elections-faq</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-query-api-beta-is-now-open-for-apps-building-on-b-o-s</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/mainnet-roadmap</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/learn/tools</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-and-sailgp-partner-on-ground-breaking-new-sports-dao</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/communityevent.near/widget/community_event</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/running-ethereum-applications-on-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-at-ethcc-step-into-the-open-web-on-the-bos</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/music-and-blockchain-introducing-the-future-of-sound</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/marieke-flament-appointed-ceo-near-foundation</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-2022-a-year-in-review</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/about/network/decentralize</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/women-in-web3-changemakers-erica-kang</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/case-studies/paras</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/orange-dao-selects-near-foundation-as-web3-startup-partner</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/devgovgigs.near/widget/devhub.entity.addon.blog.Viewer</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-wallets-evolution-in-2023</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/women-in-web3-changemakers-emily-rose-dallara</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/get-to-know-the-bos-fastauth-for-easy-web2-style-onboarding-and-account-recovery</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/octopus-network-partners-with-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/the-evolution-of-the-open-web</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-decentralization-roadmap</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/nearui.near/widget/index</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-launches-private-shard-for-enterprise</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-boosts-web3-gaming-with-new-south-korea-regional-hub-launch</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/music-and-blockchain-the-rise-of-the-new-musician</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/nearukraineguild.near/widget/votes-viewer</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/chess-game.near/widget/ChessGameLobby</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/examples</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/mantle-ecosystem-gateway-launches-on-the-near-blockchain-operating-system-b-o-s</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/refining-near-foundations-grant-approach</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-and-dropt-to-revolutionize-loyalty-and-engagement</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/frol.near/widget/LOL.pages.Main</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-bringing-chainlinks-leading-oracle-solution-to-its-open-web-ecosystem</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-and-the-graph-partnership</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-apac-day-one-scaling-local-adoption-regional-regulation-and-ai-in-focus</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-at-ethcc-highlights-sustainability-and-the-bos-take-center-stage-in-paris</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/call-for-founders-and-developers-to-qualify-your-b-o-s-apps-before-nearcon-23</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/use-cases/dao</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/nearhorizon.near/widget/Onboarding.Page</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-q4-p</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-transparency-report-q3-2022</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/update-on-the-grassroots-support-initiative</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nearcon-highlights</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-mainnet-is-now-community-operated</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/potlock.near/widget/potlock.home.main1</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/women-in-web3-changemakers-veronica-korzh</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/randomness-in-blockchain-protocols</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-and-sail-gp-elevate-mobile-fan-engagement-with-the-dock</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/how-to-convert-web-2-games-to-web-3</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-at-ethdenver-highlights</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-partners-with-bora-one-of-koreas-largest-gamefi-platforms</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/thefunpass-debuts-at-north-americas-largest-night-market-with-the-littles-and-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-announces-policy-principles</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/women-in-web3-changemakers-zoe-leavitt</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/private-transactions-on-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-education-1000-teachers-program</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-signs-up-to-the-ethereum-climate-platform</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-apac-day-2-recap-asia-gaming-trends-interoperability-and-web3-for-brands</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-and-press-start-team-to-level-up-web3-gaming</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-and-grupo-nutresa-partner-for-customer-experience-innovations-in-web3</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/with-meshflux-multimedia-art-and-gaming-explore-blockchain-technology</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/keypom-brings-frictionless-onboarding-to-near-and-web3</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-mainnet-phase-2-unrestricted-decentralized</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/icymi-scootering-through-web3-at-near-apacs-vietnam-showcase</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/binance-custody-adds-near-token-and-nep-141-standard-to-its-infrastructure</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/the-future-of-decentralized-streaming-music</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-metabuild-2-join-the-hackathon-and-build-an-app</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/mooniswap-brings-its-next-generation-amm-protocol-by-1inch-to-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/building-a-record-label-on-the-blockchain</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/case-study-near-foundations-laura-cunningham-on-the-near-horizon-startup-accelerator</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/fireblocks-provides-custody-facility-for-institutional-investors-on-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-day-at-ethdenver-ethereum-without-limits</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/evolving-near-foundations-funding-strategy</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/etherscan-will-launch-on-aurora</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/case-study-satoris-jeff-bissinger-talks-near-tasks-for-the-gig-economy</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/how-vietnam-became-a-web3-powerhouse</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-joins-multichain-to-bring-more-cross-chain-capabilities-to-the-ecosystem</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-2021-a-year-in-review</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/filecoin-launches-collaboration-with-near-to-accelerate-the-growth-of-the-web3-stack</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-launches-kenya-regional-hub-to-support-blockchain-projects-and-talent-in-africa</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/berry-club-part-ii</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-transparency-report-the-state-of-staking</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/case-study-flipside-crypto-on-building-an-analytics-platform-on-the-bos</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-ceo-transition-a-note-from-erik-trautman</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-transparency-report-december-2</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/arpit-sharma-joins-near-as-managing-director-for-india-asia-and-middle-east-expansion</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-community-in-focus-near-regional-hubs</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/rove-world-v2-simplifies-web3-ticketing-and-loyalty-for-brands</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/bitgo-becomes-first-qualified-custodian-to-support-near-protocol-and-its-assets</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/an-open-invitation-to-the-terra-community</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/introducing-seatlabnft-the-web3-startup-changing-the-ticketing-game</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/understanding-rust-lifetimes</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/shred-spots-and-near-foundation-kick-flipping-into-the-future-of-social-nfts</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-launches-smart-contract-audit-program</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/off-to-the-races-zest-launches-on-the-near-mainnet</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-at-consensus-highlights</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-x-coingecko-raffle-winner-terms-and-conditions</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/update-on-the-near-wallet-transition</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/knaq-and-near-a-new-era-of-fan-engagement-with-web3</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-launches-sustainable-learn-and-earn-program-with-coinbase</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-launches-new-validator-program-to-further-decentralize-the-network</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nearcon-2022-is-almost-here-explore-the-near-ecosystem-in-lisbon</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-and-wemade-team-up-to-accelerate-mainstream-web3-adoption</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/prediction-market-and-insurance-with-flux</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/the-near-foundations-vision-for-the-future</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/astro-launches-on-near-to-supercharge-dao-communities</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/mintbase-brings-new-open-web-wallet-tech-to-families-celebrating-raksha-bandhan</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/join-stake-wars-to-become-a-chunk-only-producer</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/the-near-token-sale-and-unforkable-community</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/ecosystem-update-on-decentralizing-governance</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-social-good-a-deep-dive-into-open-forest-protocol</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/long-range-attacks-and-a-new-fork-choice-rule</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-onboarding-with-gitpod</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-backs-hydra-ventures-to-create-web3s-first-fund-of-funds-investment-dao</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/the-authoritative-guide-to-blockchain-sharding-part-1</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/detailed-overview-of-ethereum-2-0-shard-chains-committees-proposers-and-attesters</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-and-eigen-labs-partner-to-enable-faster-cheaper-web3-transactions-for-ethereum-rollups-via-eigenlayer</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nearcon-23-lifts-off-start-your-journey-into-the-open-web</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-at-ethdenver-hackathon-bounty-winners</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundations-response-to-the-uk-crypto-asset-consultation</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nearcon-23-developer-founder-and-creative-talks-you-shouldnt-miss</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/stake-wars-episode-ii</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/mainnet-phase-i</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/avalanche-vs-the-new-iota-consensus-algorithm-with-a-touch-of-spacemesh</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-balkans-tekuno-and-mastercard-team-up-for-gamified-nft-experience</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/the-future-of-daos-tooling-standards-and-management-part-i</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-joins-flamingodao-%F0%9F%A6%A9</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/a-deep-dive-into-daos-exploring-astro-dao</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/2020-near-in-review-ecosystem-tour</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-elliptic-partnership-security</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/metabuild-2-hackathon-winners</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/2-of-near-sharding-launches</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/sailgp-launches-digital-collectibles-series-on-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundations-response-to-tornado-cash-ownership-and-regulation</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/join-us-at-nearcon-alpha-tickets-conference-lisbon</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nfts-on-near-a-deep-dive-into-paras</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/hack-the-rainbow-%F0%9F%8C%88-nears-first-massive-open-online-hackathon-aka-mooh</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-and-nansen-partner-on-on-chain-analytics-for-founders-and-investors</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-partners-with-ceramic</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/a-deep-dive-into-daos-life-changing-daos</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-and-popp-partner-on-customer-engagement-for-small-businesses</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-at-consensus-get-started-on-the-blockchain-operating-system</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-and-pipeflare-team-up-to-reshape-web3-gaming</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nfts-on-near-beyond-the-hype</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/metabuidl-hackathon-winners</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/metabuidl-build-the-metaverse-at-near-hackathon-with-1m-in-prizes</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/case-study-auroras-alex-shevchenko-on-scaling-solidity-smart-contracts</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/meet-the-builders-of-the-open-web-top-speakers-at-nearcon-23</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/the-first-near-community-town-hall-monday-september-28th</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/unsolved-problems-in-blockchain-sharding</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/winners-of-hack-the-rainbow</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/shemaroo-and-near-foundation-accelerate-web3-adoption-in-indian-media-and-entertainment</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-launches-balkans-regional-hub-to-incubate-web3-talent-and-projects</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-at-we-are-developers-world-congress-2023-build-with-bos-in-berlin</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-in-march-unchain-fund-sailgp-and-daos</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/women-of-web3-changemakers-cathy-hackl</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/welcome-to-day-0-its-just-the-beginning</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nfts-on-near-where-will-nfts-go-next</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-bridges-decentralization-interconnection</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/a-deep-dive-into-daos-reinventing-community</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/building-new-worlds-for-artists-with-nfts-paras-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/aurora-consensys-partnership-metamask-infura</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/highlights-from-near-at-paris-blockchain-week-summit</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nvab</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/how-the-near-foundation-is-supporting-network-decentralization</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/well-hello-near-academy</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-community-in-focus-web3-vs-web2-communities</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nfts-on-near-why-nft</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nears-march-town-hall-highlights</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/get-your-nearcon-tickets-now</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-validators-upgrade-decentralization</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-gaming-putting-gamers-in-the-drivers-seat</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-funding-updates-funding-beyond-grants</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-and-recur-to-make-building-on-web3-easy-for-web2-brands</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/guild-program-launch</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-partners-with-absolute-labs-to-accelerate-how-brands-connect-with-customers-in-web3</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/an-open-invitation-to-the-harmony-community</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/update-on-near-decentralized-funding-daos-and-accelerator</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-at-ethdenver-the-blockchain-operating-system-near-day-and-more</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-hackathon-at-ready-layer-one-winners-announced</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/welcome-to-near-con</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/hacking-a-new-world-with-metabuild-iii</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nears-road-to-decentralization-empowering-the-guild-community</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/why-nearcon-is-the-must-see-global-web3-event-of-2023</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-pr-roundup-for-march</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-and-alibaba-cloud-team-up-to-grow-the-open-web</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-metabuild-2-and-brave-head-to-ethdenver</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-transparency-report-november-25</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/why-doesnt-near-just-replicate-ethereum-serenity-design</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/berry-cards</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/women-in-web3-changemakers-bridget-greenwood</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-pr-roundup-for-february</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/how-blockchain-will-save-the-creator-economy</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-at-davos-for-world-economic-forum</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/introducing-endlesss-gamifying-music-creation-with-nfts</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-at-ethdenver-building-a-multi-chain-future</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nft-marketplace-for-hip-hop-heads-launches-on-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nearcon-2022-a-global-experience-for-builders-and-creators</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-partners-with-mask-network</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/an-update-on-the-near-validator-upgrade</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-now-integrated-into-ledger-live-for-more-security-and-ownership</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/decentralized-storage-for-dapp-developers</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/announcing-near-grants-pilot-program</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/introducing-4-apps-building-on-near-at-consensus-distributed</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/favicon.ico</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-developer-research-validating-the-near-devx-tech-stack-round-2</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/deadmau5-launches-nft-partnership-with-mintbase-and-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/first-fan-owned-team-launches-on-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-weekly-on-chain-data-report-december-16</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/funberryclub</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-gaming-how-web3-is-disrupting-gaming</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/future-of-blockchain-hackathon-near-recap</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-launches-near-da-to-offer-secure-cost-effective-data-availability-for-eth-rollups-and-ethereum-developers)</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/armored-kingdom-launches-new-scifi-fantasy-media-platform-on-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/register-for-nears-june-town-hall-near-at-consensus</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/ready-layer-one-rewind</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/toward-a-better-planet-green-nfts</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/octopus-network-seed-funding-round-complete</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-is-going-to-ethdenver</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/important-update-for-near-wallet-users-and-developers</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/a-time-for-conviction</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/cvvctop50near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-lunch-learn-ep-03-light-clients-in-proof-of-stake-systems</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-at-ethdenver-2022-highlights</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-social-good-change-through-crypto</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-meet-now-supporting-local-and-regional-events-globally</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/the-future-of-daos-daos-at-work-and-irl-part-ii</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/community-update-july-17th-2020</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/community-update-community-token-sale-mintbase-flux-phase-1-0-%F0%9F%8C%88-rainbow-bridge</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-funding-team-report-october-2022</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/community-update-beyond-launch</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-in-may-10m-wallets-surpassed-sailgp-hits-the-waves-and-more</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-and-seracle-team-to-nurture-the-web3-ecosystem-with-devops-efficiency</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/community-update-near-edu-flux-beta-program-and-googuild</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/were-pausing-stake-wars</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/inside-the-tech-nft-hiphop</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-welcomes-fresh-executive-talent-to-accelerate-its-global-reach</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-q4-update-ecosystem-sharding-launch</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/community-update-june-5th-2020</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-launches-stake-farming-to-unlock-ecosystem-rewards</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/dragonfly-capital</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/fundraise</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-social-good-the-future-of-social-good-and-crypto</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/august-in-review-javascript-sdk-near-digital-collective-launch-and-nearcon-updates</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/author/alex</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-hires-chris-ghent-to-lead-global-brand-and-communications-efforts</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-and-startup-wise-guys-partner-on-metabuilds-pre-accelerator-program</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-blockchain-operating-system-is-now-live-on-near-org</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/stake-wars-iii-is-halfway-to-the-finish-line-what-does-this-mean-for-nears-sharding</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/on-usability-of-blockchain-applications</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nears-february-town-hall-highlights</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/why-web3-is-needed-more-than-ever</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-community-in-focus-decentralized-community-building-on-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/limitations-of-zilliqas-sharding-approach</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/trusttoken-bridges-tusd-to-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/open-sourcing-near-client</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/tag/ecosystem</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-validator-upgrade-allows-hundreds-to-help-secure-the-network</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/remote-development-and-debugging-of-rust-with-clion</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/an-update-on-near-wallet-transition</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/so-what-exactly-is-vlads-sharding-poc-doing</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/open-call-for-near-accelerator-service-partners</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/category/partnerships</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nears-bos-impact-at-we-are-developers-2023-world-congress</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-social-good-bringing-web3-to-the-fringes</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nears-april-town-hall-highlights</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-weekly-on-chain-data-report-december-23</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/openwebchinaama</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nearcon-zero</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/minecraft-mint-nft-dev-rel-tutorial-near-how-to</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/snark-art-digital-art-platform</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-community-update-february-22-2019</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-funding-team-report-september-2022</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-partners-with-vortex-gaming-a-web3-subsidiary-of-koreas-largest-gaming-community-inven</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/nears-january-town-hall-recap</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/a-year-on-near-nearcon-retrospective</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-powers-voting-for-the-djooky-music-awards</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/community-update-april-24th-2020</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/armored-kingdom-brave-javascript-highlights-from-near-consensus</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/use-case-distributed-identity-solutions</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-community-update-march-13th-2020</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/community-update-zest-hack-the-rainbow</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-transparency-report-december-9</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-after-nearcon-in-numbers</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/stake-wars-week-3-retro</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-api-js-new-release-javascript</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/why-nears-ecosystem-remains-primed-for-growth-in-2022</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/music-application-architecture</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-pr-roundup-for-january</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/infura-brings-its-leading-eth-dev-platform-to-near-protocol</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-in-april-sweatcoin-kenya-regional-hub-and-more</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/register-for-nears-february-town-hall-near-is-global</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/community-update-mainnet-phase-i-%F0%9F%9A%80-hack-the-rainbow-%F0%9F%8C%88-owc-demo-day</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/july-in-review-700-projects-milestone-nearcon-tickets-and-women-in-web3</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/metabuidl-launch-highlights</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/get-in-my-beta-program-july-12-2019</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-in-hong-kong-create-without-limits</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/john-smith-joins-near-as-ciso-to-redefine-safety-in-the-blockchain-ecosystem</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/use-case-spotlight-nuclo</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/rownd-and-near-foundation-are-cracking-the-code-of-web3-onboarding</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-horizon-and-outlier-ventures-create-base-camp-accelerator-to-propel-web3-startups</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/tessab-blockchain</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-gaming-a-deep-dive-into-op-games</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-horizon-and-encode-club-accelerating-blockchain-mastery-for-builders</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/happy-hacking-november-15th-2019</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/p2p-validator-joins-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/like-totally-random-august-12-2019</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/taco-labs-and-near-foundation-to-give-shopify-retailers-next-gen-customer-loyalty-programs</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/encode-x-near-horizon-bootcamp-your-mission-to-master-web3-rust-contracts</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-protocol-roadmap-2023-4-the-next-2-years-of-near%25ef%25bf%25bc</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-launches-near-horizon/'</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/refer-and-earn-2022-q2-report</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-talks-at-ready-layer-one</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-joins-multichain-to-bring-more-cross-chain-ca</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/our-last-update-december-13th-2019</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/international-cricket-council-and-near-foundation-sign-m%5B%E2%80%A6%5Dyear-partnership-to-boost-global-fan-engagement-through-web3</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-in-february-ethdenver-pagoda-launch-and-more</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-launches-1-million-marketing-competition-and-virtual-conference</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/tag/mastercard</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/register-for-nears-march-town-hall-daos-on-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-community-update-february-14th-2020</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/the-future-of-blockchain-hackathon</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/refer-and-earn-guidelines-update-q3-2022</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/%d1%83%d0%bd%d1%96%d0%ba%d0%b0%d0%bb%d1%8c%d0%bd%d0%b0-%d0%bc%d0%be%d0%b6%d0%bb%d0%b8%d0%b2%d1%96%d1%81%d1%82%d1%8c-%d0%b4%d0%bb%d1%8f-%d1%83%d0%ba%d1%80%d0%b0%d1%97%d0%bd%d1%86%d1%96%d0%b2-%d0%b1</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/tag/favicon.ico</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>
            ${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-joins-forces-with-mirae-asset-for-the-next-leap-in-web3-finance</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/open-call-for-near-horizon-content-creators</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/tag/tekuno</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/a-developers-blockchain</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-community-update-march-27th-2020</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/the-future-of-community-on-near</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/tag/transparency</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/near-foundation-launches-new-ama-series</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
    <url>
        <loc>${process.env.NEXT_PUBLIC_HOSTNAME}/blog/software-eating-financial-contracts</loc>
        <lastmod>2024-02-13</lastmod>
    </url>
</urlset>
   `;
}

type SiteMap = {
  props: object;
};

function SiteMap() {
  // getServerSideProps will do the heavy lifting
}

export function getServerSideProps({ res }: { res: any }): SiteMap {
  const sitemap = generateSiteMap();

  res.setHeader('Content-Type', 'text/xml');

  res.write(sitemap);
  res.end();

  return {
    props: {},
  };
}

export default SiteMap;
