const ROUTE_CONFIG = {
  agave: {
    type: 'lending',
    theme: {
      '--switch-color': 'rgb(64, 179, 144)',
      '--button-text-color': '#fff',
      '--supply-color': 'rgb(1, 157, 139)',
      '--yours-table-title': '#fff',
      '--borrow-color': 'rgb(190, 75, 192)',
      '--withdraw-bg-color': 'rgb(1, 157, 139)',
      '--withdraw-border-color': 'rgb(1, 157, 139)',
      '--withdraw-bg-hover-color': 'rgb(1, 157, 139, 0.8)',
      '--repay-bg-color': 'rgb(1, 157, 139)',
      '--repay-border-color': 'rgb(1, 157, 139)',
      '--repay-bg-hover-color': 'rgb(1, 157, 139, 0.8)',
    },
  },
  benqi: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  cream: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  'granary-finance': {
    type: 'lending',
    theme: {
      '--switch-color': '#91C53E',
      '--button-text-color': '#fff',
      '--supply-color': '#FFFFFF',
      '--yours-table-title': '#FFFFFF',
      '--borrow-color': '#FF8EE6',
      '--withdraw-bg-color': '#91C53E',
      '--withdraw-border-color': '#91C53E',
      '--withdraw-bg-hover-color': '#91C53E',
      '--repay-bg-color': '#CA55B0',
      '--repay-border-color': '#CA55B0',
      '--repay-bg-hover-color': '#CA55B0',
    },
  },
  'iron-bank': {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  'layer-bank': {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  lendle: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  'mendi-finance': {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  moonwell: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  radiant: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  'reactor-fusion': {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  sonne: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  venus: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  avage: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  'valas-finance': {
    type: 'lending',
    theme: {
      '--switch-color': '#91C53E',
      '--button-text-color': '#fff',
      '--supply-color': '#FFFFFF',
      '--yours-table-title': '#FFFFFF',
      '--borrow-color': '#FF8EE6',
      '--withdraw-bg-color': '#91C53E',
      '--withdraw-border-color': '#91C53E',
      '--withdraw-bg-hover-color': '#91C53E',
      '--repay-bg-color': '#CA55B0',
      '--repay-border-color': '#CA55B0',
      '--repay-bg-hover-color': '#CA55B0',
    },
  },
  'tender-finance': {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  'we-piggy': {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  filda: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  'trader-joe-lend': {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  'lodestar-v1': {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  liqee: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  'shoebill-v2': {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  'gravita-protocol': {
    type: 'lending',
    theme: {
      '--switch-color': '#D079FF',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '#D079FF',
      '--repay-border-color': '#D079FF',
      '--repay-bg-hover-color': '',
    },
  },
};

export default ROUTE_CONFIG;
