const ROUTE_CONFIG = {
  agave: {
    type: 'lending',
    theme: {
      '--button-color': '#019D8B',
      '--switch-color': '#019D8B',
      '--button-text-color': '#fff',
      '--supply-color': '#019D8B',
      '--yours-table-title': '#fff',
      '--borrow-color': '#019D8B',
      '--withdraw-bg-color': '#019D8B',
      '--withdraw-border-color': '#019D8B',
      '--withdraw-bg-hover-color': '#019D8B',
      '--repay-bg-color': '#019D8B',
      '--repay-border-color': '#019D8B',
      '--repay-bg-hover-color': '#019D8B',
      '--claim-bg-hover-color': '#019D8B',
      '--claim-bg-color': '#019D8B',
      '--claim-border-color': '#019D8B',
      '--withdraw-color': '#fff',
      '--replay-color': '#fff',
      '--claim-color': '#fff',
    },
  },
  benqi: {
    type: 'lending',
    theme: {
      '--button-color': '#02B3ED',
      '--switch-color': '#02B3ED',
      '--button-text-color': '#000000',
      '--supply-color': '#02B3ED',
      '--yours-table-title': '#fff',
      '--borrow-color': '#02B3ED',
      '--withdraw-bg-color': '#02B3ED',
      '--withdraw-border-color': '#02B3ED',
      '--withdraw-bg-hover-color': '#02B3ED',
      '--repay-bg-color': '#02B3ED',
      '--repay-border-color': '#02B3ED',
      '--repay-bg-hover-color': '#02B3ED',
      '--claim-bg-hover-color': '#02B3ED',
      '--claim-bg-color': '#02B3ED',
      '--claim-border-color': '#02B3ED',
      '--withdraw-color': '#000000',
      '--replay-color': '#000000',
      '--claim-color': '#000000',
    },
  },
  cream: {
    type: 'lending',
    theme: {
      '--button-color': '#69E2DB',
      '--switch-color': '#69E2DB',
      '--button-text-color': '#000000',
      '--supply-color': '#69E2DB',
      '--yours-table-title': '#fff',
      '--borrow-color': '#FFB8D2',
      '--withdraw-bg-color': '#69E2DB',
      '--withdraw-border-color': '#69E2DB',
      '--withdraw-bg-hover-color': '#69E2DB',
      '--repay-bg-color': '#FFB8D2',
      '--repay-border-color': '#FFB8D2',
      '--repay-bg-hover-color': '#FFB8D2',
      '--claim-bg-hover-color': '#69E2DB',
      '--claim-bg-color': '#69E2DB',
      '--claim-border-color': '#69E2DB',
      '--withdraw-color': '#000000',
      '--replay-color': '#000000',
      '--claim-color': '#000000',
    },
  },
  'granary-finance': {
    type: 'lending',
    theme: {
      '--button-color': '#91C53E',
      '--switch-color': '#91C53E',
      '--button-text-color': '#fff',
      '--supply-color': '#FFFFFF',
      '--yours-table-title': '#FFFFFF',
      '--borrow-color': '#FF8EE6',
      '--withdraw-bg-color': '#91C53E',
      '--withdraw-border-color': '#91C53E',
      '--withdraw-bg-hover-color': '#91C53E',
      '--repay-bg-color': '#CA55B0',
      '--repay-border-color': '#CA55B0',
      '--repay-bg-hover-color': '#CA55B0',
      '--claim-bg-hover-color': '#91C53E',
      '--claim-bg-color': '#91C53E',
      '--claim-border-color': '#91C53E',
      '--withdraw-color': '#fff',
      '--replay-color': '#fff',
      '--claim-color': '#fff',
    },
  },
  'iron-bank': {
    type: 'lending',
    theme: {
      '--button-color': 'rgba(0, 255, 66, 0.2)',
      '--switch-color': 'rgba(0, 255, 66, 0.2)',
      '--button-text-color': '#FFFFFF',
      '--supply-color': 'rgba(0, 255, 66, 0.2)',
      '--yours-table-title': '#FFFFFF',
      '--borrow-color': '#FFFFFF',
      '--withdraw-bg-color': 'rgba(0, 255, 66, 0.2)',
      '--withdraw-border-color': '#96FFB1',
      '--withdraw-bg-hover-color': 'rgba(0, 255, 66, 0.2)',
      '--repay-bg-color': 'rgba(0, 255, 66, 0.2)',
      '--repay-border-color': '#96FFB1',
      '--repay-bg-hover-color': 'rgba(0, 255, 66, 0.2)',
      '--claim-bg-hover-color': 'rgba(0, 255, 66, 0.2)',
      '--claim-bg-color': 'rgba(0, 255, 66, 0.2)',
      '--claim-border-color': '#96FFB1',
      '--withdraw-color': '#FFFFFF',
      '--replay-color': '#FFFFFF',
      '--claim-color': '#FFFFFF',
    },
  },
  'layer-bank': {
    type: 'lending',
    theme: {
      '--button-color': '#2B55D0',
      '--switch-color': '#2B55D0',
      '--button-text-color': '#FFFFFF',
      '--supply-color': '#2B55D0',
      '--yours-table-title': '#FFFFFF',
      '--borrow-color': '#2B55D0',
      '--withdraw-bg-color': '#2B55D0',
      '--withdraw-border-color': '#2B55D0',
      '--withdraw-bg-hover-color': '#2B55D0',
      '--repay-bg-color': '#2B55D0',
      '--repay-border-color': '#2B55D0',
      '--repay-bg-hover-color': '#2B55D0',
      '--claim-bg-hover-color': '#2B55D0',
      '--claim-bg-color': '#2B55D0',
      '--claim-border-color': '#2B55D0',
      '--withdraw-color': '#2B55D0',
      '--replay-color': '#FFFFFF',
      '--claim-color': '#FFFFFF',
    },
  },
  lendle: {
    type: 'lending',
    theme: {
      '--button-color': '#9E77ED',
      '--switch-color': '#9E77ED',
      '--button-text-color': '#FFFFFF',
      '--supply-color': '#9E77ED',
      '--yours-table-title': '#FFFFFF',
      '--borrow-color': '#9E77ED',
      '--withdraw-bg-color': '#9E77ED',
      '--withdraw-border-color': '#9E77ED',
      '--withdraw-bg-hover-color': '#9E77ED',
      '--repay-bg-color': '#9E77ED',
      '--repay-border-color': '#9E77ED',
      '--repay-bg-hover-color': '#9E77ED',
      '--claim-bg-hover-color': '#9E77ED',
      '--claim-bg-color': '#9E77ED',
      '--claim-border-color': '#9E77ED',
      '--withdraw-color': '#FFFFFF',
      '--replay-color': '#FFFFFF',
      '--claim-color': '#FFFFFF',
    },
  },
  'mendi-finance': {
    type: 'lending',
    theme: {
      '--button-color': 'transparent',
      '--switch-color': 'transparent',
      '--button-text-color': '#FEF1EC',
      '--supply-color': 'transparent',
      '--yours-table-title': '#FEF1EC',
      '--borrow-color': 'transparent',
      '--withdraw-bg-color': 'transparent',
      '--withdraw-border-color': 'transparent',
      '--withdraw-bg-hover-color': '#38CDFF',
      '--repay-bg-color': 'transparent',
      '--repay-border-color': '#38CDFF',
      '--repay-bg-hover-color': 'transparent',
      '--claim-bg-hover-color': 'transparent',
      '--claim-bg-color': 'transparent',
      '--claim-border-color': '#38CDFF',
      '--withdraw-color': '#FEF1EC',
      '--replay-color': '#FEF1EC',
      '--claim-color': '#FEF1EC',
    },
  },
  moonwell: {
    type: 'lending',
    theme: {
      '--button-color': '#007AFF',
      '--switch-color': '#007AFF',
      '--button-text-color': '#FFFFFF',
      '--supply-color': '#007AFF',
      '--yours-table-title': '#FFFFFF',
      '--borrow-color': '#007AFF',
      '--withdraw-bg-color': '#007AFF',
      '--withdraw-border-color': '#007AFF',
      '--withdraw-bg-hover-color': '#007AFF',
      '--repay-bg-color': '#007AFF',
      '--repay-border-color': '#007AFF',
      '--repay-bg-hover-color': '#007AFF',
      '--claim-bg-hover-color': '#007AFF',
      '--claim-bg-color': 'transparent',
      '--claim-border-color': 'rgba(255, 255, 255, 0.35)',
      '--withdraw-color': '#FFFFFF',
      '--replay-color': '#FFFFFF',
      '--claim-color': '#FFFFFF',
    },
  },
  radiant: {
    type: 'lending',
    theme: {
      '--button-color': 'transparent',
      '--switch-color': 'transparent',
      '--button-text-color': '#9A80FE',
      '--supply-color': 'transparent',
      '--yours-table-title': '#fff',
      '--borrow-color': '#9A80FE',
      '--withdraw-bg-color': 'transparent',
      '--withdraw-border-color': 'transparent',
      '--withdraw-bg-hover-color': 'transparent',
      '--repay-bg-color': '#9A80FE',
      '--repay-border-color': '#9A80FE',
      '--repay-bg-hover-color': '#9A80FE',
      '--claim-bg-hover-color': '#9A80FE',
      '--claim-bg-color': '#9A80FE',
      '--claim-border-color': '#9A80FE',
      '--withdraw-color': '#9A80FE',
      '--replay-color': '#fff',
      '--claim-color': '#fff',
    },
  },
  'reactor-fusion': {
    type: 'lending',
    theme: {
      '--button-color': 'transparent',
      '--switch-color': 'transparent',
      '--button-text-color': '#FFFFFF',
      '--supply-color': 'transparent',
      '--yours-table-title': '#FFFFFF',
      '--borrow-color': 'transparent',
      '--withdraw-bg-color': 'transparent',
      '--withdraw-border-color': 'rgba(255, 255, 255, 0.7)',
      '--withdraw-bg-hover-color': 'transparent',
      '--repay-bg-color': 'transparent',
      '--repay-border-color': 'rgba(255, 255, 255, 0.7)',
      '--repay-bg-hover-color': 'transparent',
      '--claim-bg-hover-color': 'transparent',
      '--claim-bg-color': 'transparent',
      '--claim-border-color': 'rgba(255, 255, 255, 0.7)',
      '--withdraw-color': '#FFFFFF',
      '--replay-color': '#FFFFFF',
      '--claim-color': '#FFFFFF',
    },
  },
  sonne: {
    type: 'lending',
    theme: {
      '--button-color': 'transparent',
      '--switch-color': 'transparent',
      '--button-text-color': '#FEF1EC',
      '--supply-color': 'transparent',
      '--yours-table-title': '#FEF1EC',
      '--borrow-color': 'transparent',
      '--withdraw-bg-color': 'transparent',
      '--withdraw-border-color': '#FEA668',
      '--withdraw-bg-hover-color': 'transparent',
      '--repay-bg-color': 'transparent',
      '--repay-border-color': '#FEA668',
      '--repay-bg-hover-color': 'transparent',
      '--claim-bg-hover-color': 'transparent',
      '--claim-bg-color': 'transparent',
      '--claim-border-color': '#FD684E',
      '--withdraw-color': '#FEF1EC',
      '--replay-color': '#FEF1EC',
      '--claim-color': '#FEF1EC',
    },
  },
  venus: {
    type: 'lending',
    theme: {
      '--button-color': '#3a78ff',
      '--switch-color': '#3a78ff',
      '--button-text-color': '#fff',
      '--supply-color': '#3a78ff',
      '--yours-table-title': '#fff',
      '--borrow-color': '#3a78ff',
      '--withdraw-bg-color': '#3a78ff',
      '--withdraw-border-color': '#3a78ff',
      '--withdraw-bg-hover-color': '#3a78ff',
      '--repay-bg-color': '#3a78ff',
      '--repay-border-color': '#3a78ff',
      '--repay-bg-hover-color': '#3a78ff',
      '--claim-bg-hover-color': '#3a78ff',
      '--claim-bg-color': '#3a78ff',
      '--claim-border-color': '#3a78ff',
      '--withdraw-color': '#fff',
      '--replay-color': '#fff',
      '--claim-color': '#fff',
    },
  },
  'valas-finance': {
    type: 'lending',
    theme: {
      '--button-color': '#91C53E',
      '--switch-color': '#91C53E',
      '--button-text-color': '#fff',
      '--supply-color': '#FFFFFF',
      '--yours-table-title': '#FFFFFF',
      '--borrow-color': '#FF8EE6',
      '--withdraw-bg-color': '#91C53E',
      '--withdraw-border-color': '#91C53E',
      '--withdraw-bg-hover-color': '#91C53E',
      '--repay-bg-color': '#CA55B0',
      '--repay-border-color': '#CA55B0',
      '--repay-bg-hover-color': '#CA55B0',
      '--claim-bg-hover-color': '#91C53E',
      '--claim-bg-color': '#91C53E',
      '--claim-border-color': '#91C53E',
      '--withdraw-color': '#fff',
      '--replay-color': '#fff',
      '--claim-color': '#fff',
    },
  },
  'tender-finance': {
    type: 'lending',
    theme: {
      '--button-color': '#16F195',
      '--switch-color': '#16F195',
      '--button-text-color': '#fff',
      '--supply-color': '#16F195',
      '--yours-table-title': '#fff',
      '--borrow-color': '#00E0FF',
      '--withdraw-bg-color': '#16F195',
      '--withdraw-border-color': '#16F195',
      '--withdraw-bg-hover-color': 'rgba(22, 241, 149, 0.8)',
      '--repay-bg-color': '#00E0FF',
      '--repay-border-color': '#00E0FF',
      '--repay-bg-hover-color': 'rgba(0, 224, 255, 0.8)',
      '--claim-bg-hover-color': 'transparent',
      '--claim-bg-color': 'transparent',
      '--claim-border-color': '#16F195',
      '--withdraw-color': '#010604',
      '--replay-color': '#010604',
      '--claim-color': '#16F195',
    },
  },
  'we-piggy': {
    type: 'lending',
    theme: {
      '--button-color': '#FF4596',
      '--switch-color': '#FF4596',
      '--button-text-color': '#fff',
      '--supply-color': '#FF4596',
      '--yours-table-title': '#fff',
      '--borrow-color': '#5753BE',
      '--withdraw-bg-color': '#FF4596',
      '--withdraw-border-color': '#FF4596',
      '--withdraw-bg-hover-color': 'rgba(255, 69, 150, 0.8)',
      '--repay-bg-color': '#5753BE',
      '--repay-border-color': '#5753BE',
      '--repay-bg-hover-color': 'rgba(87, 83, 190, 0.8)',
      '--claim-bg-hover-color': 'rgba(255, 69, 150, 0.8)',
      '--claim-bg-color': '#FF4596',
      '--claim-border-color': '#FF4596',
      '--withdraw-color': '#fff',
      '--replay-color': '#fff',
      '--claim-color': '#fff',
    },
  },
  filda: {
    type: 'lending',
    theme: {
      '--button-color': '#24B4FF',
      '--switch-color': '#24B4FF',
      '--button-text-color': '#fff',
      '--supply-color': '#24B4FF33',
      '--yours-table-title': '#fff',
      '--borrow-color': '#DC35FE',
      '--withdraw-bg-color': 'rgba(220, 53, 254, 0.20)',
      '--withdraw-border-color': '#24B4FF',
      '--withdraw-bg-hover-color': 'rgba(220, 53, 254, 0.40)',
      '--repay-bg-color': 'rgba(220, 53, 254, 0.20)',
      '--repay-border-color': '#DC35FE',
      '--repay-bg-hover-color': 'rgba(220, 53, 254, 0.40)',
      '--claim-bg-hover-color': 'linear-gradient(to right, rgba(46, 169, 255, 0.8), rgba(135, 41, 255, 0.8))',
      '--claim-bg-color': 'linear-gradient(to right, #2EA9FF, #8729FF)',
      '--claim-border-color': '#2EA9FF',
      '--withdraw-color': '#fff',
      '--replay-color': '#fff',
      '--claim-color': '#fff',
    },
  },
  'trader-joe-lend': {
    type: 'lending',
    theme: {
      '--button-color': '#4eb6ff',
      '--switch-color': '#4eb6ff',
      '--button-text-color': '#131313',
      '--supply-color': '#4eb6ff',
      '--yours-table-title': '#fff',
      '--borrow-color': '#4eb6ff',
      '--withdraw-bg-color': '#4eb6ff',
      '--withdraw-border-color': '#4eb6ff',
      '--withdraw-bg-hover-color': '#4eb6ff',
      '--repay-bg-color': '#4eb6ff',
      '--repay-border-color': '#4eb6ff',
      '--repay-bg-hover-color': '#4eb6ff',
      '--claim-bg-hover-color': '#4eb6ff',
      '--claim-bg-color': '#4eb6ff',
      '--claim-border-color': '#4eb6ff',
      '--withdraw-color': '#131313',
      '--replay-color': '#131313',
      '--claim-color': '#131313',
    },
  },
  'lodestar-v1': {
    type: 'lending',
    theme: {
      '--button-color': '#E5D540',
      '--switch-color': '#E5D540',
      '--button-text-color': '#000',
      '--supply-color': '#E5D540',
      '--yours-table-title': '#E5D540',
      '--borrow-color': '#E69E40',
      '--withdraw-bg-color': '#E5D540',
      '--withdraw-border-color': '#E5D540',
      '--withdraw-bg-hover-color': 'rgba(229, 213, 64, 0.8)',
      '--repay-bg-color': '#E69E40',
      '--repay-border-color': '#E69E40',
      '--repay-bg-hover-color': 'rgba(230, 158, 64, 0.8)',
      '--claim-bg-hover-color': 'rgba(229, 213, 64, 0.4)',
      '--claim-bg-color': 'rgba(229, 213, 64, 0.2)',
      '--claim-border-color': 'rgba(229, 213, 64, 0.2)',
      '--withdraw-color': '#000',
      '--replay-color': '#000',
      '--claim-color': '#E5D540',
    },
  },
  liqee: {
    type: 'lending',
    theme: {
      '--button-color': 'linear-gradient(to right, rgb(237,114,107), rgba(255,160,94))',
      '--switch-color': 'linear-gradient(to right, rgb(237,114,107), rgba(255,160,94))',
      '--button-text-color': '#fff',
      '--supply-color': '#ffe8d8',
      '--yours-table-title': '#ff8079',
      '--borrow-color': '#ff8079',
      '--withdraw-bg-color': '#ffe8d8',
      '--withdraw-border-color': '#ffe8d8',
      '--withdraw-bg-hover-color': '#ffe8d8',
      '--repay-bg-color': '#ff8079',
      '--repay-border-color': '#ff8079',
      '--repay-bg-hover-color': '#ff8079',
      '--claim-bg-hover-color': '#ffe8d8',
      '--claim-bg-color': '#ffe8d8',
      '--claim-border-color': '#ffe8d8',
      '--withdraw-color': '#fff',
      '--replay-color': '#fff',
      '--claim-color': '#fff',
    },
  },
  'shoebill-v2': {
    type: 'lending',
    theme: {
      '--button-color': '#4eb6ff',
      '--switch-color': '#4eb6ff',
      '--button-text-color': '#131313',
      '--supply-color': '#4eb6ff',
      '--yours-table-title': '#fff',
      '--borrow-color': '#4eb6ff',
      '--withdraw-bg-color': '#4eb6ff',
      '--withdraw-border-color': '#4eb6ff',
      '--withdraw-bg-hover-color': '#4eb6ff',
      '--repay-bg-color': '#4eb6ff',
      '--repay-border-color': '#4eb6ff',
      '--repay-bg-hover-color': '#4eb6ff',
      '--claim-bg-hover-color': '#4eb6ff',
      '--claim-bg-color': '#4eb6ff',
      '--claim-border-color': '#4eb6ff',
      '--withdraw-color': '#131313',
      '--replay-color': '#131313',
      '--claim-color': '#131313',
    },
  },
  'gravita-protocol': {
    type: 'lending',
    theme: {
      '--button-color': '',
      '--switch-color': '#D079FF',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '#D079FF',
      '--repay-border-color': '#D079FF',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
  'preon-finance': {
    type: 'lending',
    theme: {
      '--button-color': '',
      '--switch-color': '#c157f9',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '#c157f9',
      '--repay-border-color': '#c157f9',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
  'ethos-finance': {
    type: 'lending',
    theme: {
      '--button-color': '',
      '--switch-color': '#c157f9',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '#c157f9',
      '--repay-border-color': '#c157f9',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
};

export default ROUTE_CONFIG;
