const ROUTE_CONFIG = {
  agave: {
    type: 'lending',
    theme: {
      '--switch-color': 'rgb(64, 179, 144)',
      '--button-text-color': '#fff',
      '--supply-color': 'rgb(1, 157, 139)',
      '--yours-table-title': '#fff',
      '--borrow-color': 'rgb(190, 75, 192)',
      '--withdraw-bg-color': 'rgb(1, 157, 139)',
      '--withdraw-border-color': 'rgb(1, 157, 139)',
      '--withdraw-bg-hover-color': 'rgb(1, 157, 139, 0.8)',
      '--repay-bg-color': 'rgb(1, 157, 139)',
      '--repay-border-color': 'rgb(1, 157, 139)',
      '--repay-bg-hover-color': 'rgb(1, 157, 139, 0.8)',
      '--claim-bg-hover-color': 'rgb(1, 157, 139)',
      '--claim-bg-color': 'rgb(1, 157, 139)',
      '--claim-border-color': 'rgb(1, 157, 139)',
      '--withdraw-color': '#fff',
      '--replay-color': '#fff',
      '--claim-color': '#fff',
    },
  },
  benqi: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
  cream: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
  'granary-finance': {
    type: 'lending',
    theme: {
      '--switch-color': '#91C53E',
      '--button-text-color': '#fff',
      '--supply-color': '#FFFFFF',
      '--yours-table-title': '#FFFFFF',
      '--borrow-color': '#FF8EE6',
      '--withdraw-bg-color': '#91C53E',
      '--withdraw-border-color': '#91C53E',
      '--withdraw-bg-hover-color': '#91C53E',
      '--repay-bg-color': '#CA55B0',
      '--repay-border-color': '#CA55B0',
      '--repay-bg-hover-color': '#CA55B0',
      '--claim-bg-hover-color': '#91C53E',
      '--claim-bg-color': '#91C53E',
      '--claim-border-color': '#91C53E',
      '--withdraw-color': '#fff',
      '--replay-color': '#fff',
      '--claim-color': '#fff',
    },
  },
  'iron-bank': {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
  'layer-bank': {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
  lendle: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
  'mendi-finance': {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
  moonwell: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
  radiant: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
  'reactor-fusion': {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
  sonne: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
  venus: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
  avage: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
  'valas-finance': {
    type: 'lending',
    theme: {
      '--switch-color': '#91C53E',
      '--button-text-color': '#fff',
      '--supply-color': '#FFFFFF',
      '--yours-table-title': '#FFFFFF',
      '--borrow-color': '#FF8EE6',
      '--withdraw-bg-color': '#91C53E',
      '--withdraw-border-color': '#91C53E',
      '--withdraw-bg-hover-color': '#91C53E',
      '--repay-bg-color': '#CA55B0',
      '--repay-border-color': '#CA55B0',
      '--repay-bg-hover-color': '#CA55B0',
      '--claim-bg-hover-color': '#91C53E',
      '--claim-bg-color': '#91C53E',
      '--claim-border-color': '#91C53E',
      '--withdraw-color': '#fff',
      '--replay-color': '#fff',
      '--claim-color': '#fff',
    },
  },
  'tender-finance': {
    type: 'lending',
    theme: {
      '--switch-color': '#16F195',
      '--button-text-color': '#fff',
      '--supply-color': '#16F195',
      '--yours-table-title': '#fff',
      '--borrow-color': '#00E0FF',
      '--withdraw-bg-color': '#16F195',
      '--withdraw-border-color': '#16F195',
      '--withdraw-bg-hover-color': 'rgba(22, 241, 149, 0.8)',
      '--repay-bg-color': '#00E0FF',
      '--repay-border-color': '#00E0FF',
      '--repay-bg-hover-color': 'rgba(0, 224, 255, 0.8)',
      '--claim-bg-hover-color': 'transparent',
      '--claim-bg-color': 'transparent',
      '--claim-border-color': '#16F195',
      '--withdraw-color': '#010604',
      '--replay-color': '#010604',
      '--claim-color': '#16F195',
    },
  },
  'we-piggy': {
    type: 'lending',
    theme: {
      '--switch-color': '#FF4596',
      '--button-text-color': '#fff',
      '--supply-color': '#FF4596',
      '--yours-table-title': '#fff',
      '--borrow-color': '#5753BE',
      '--withdraw-bg-color': '#FF4596',
      '--withdraw-border-color': '#FF4596',
      '--withdraw-bg-hover-color': 'rgba(255, 69, 150, 0.8)',
      '--repay-bg-color': '#5753BE',
      '--repay-border-color': '#5753BE',
      '--repay-bg-hover-color': 'rgba(87, 83, 190, 0.8)',
      '--claim-bg-hover-color': 'rgba(255, 69, 150, 0.8)',
      '--claim-bg-color': '#FF4596',
      '--claim-border-color': '#FF4596',
      '--withdraw-color': '#fff',
      '--replay-color': '#fff',
      '--claim-color': '#fff',
    },
  },
  filda: {
    type: 'lending',
    theme: {
      '--switch-color': '#24B4FF',
      '--button-text-color': '#fff',
      '--supply-color': '#24B4FF33',
      '--yours-table-title': '#fff',
      '--borrow-color': '#DC35FE',
      '--withdraw-bg-color': 'rgba(220, 53, 254, 0.20)',
      '--withdraw-border-color': '#24B4FF',
      '--withdraw-bg-hover-color': 'rgba(220, 53, 254, 0.40)',
      '--repay-bg-color': 'rgba(220, 53, 254, 0.20)',
      '--repay-border-color': '#DC35FE',
      '--repay-bg-hover-color': 'rgba(220, 53, 254, 0.40)',
      '--claim-bg-hover-color': 'linear-gradient(to right, rgba(46, 169, 255, 0.8), rgba(135, 41, 255, 0.8))',
      '--claim-bg-color': 'linear-gradient(to right, #2EA9FF, #8729FF)',
      '--claim-border-color': '#2EA9FF',
      '--withdraw-color': '#fff',
      '--replay-color': '#fff',
      '--claim-color': '#fff',
    },
  },
  'trader-joe-lend': {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
    },
  },
  'lodestar-v1': {
    type: 'lending',
    theme: {
      '--switch-color': '#E5D540',
      '--button-text-color': '#000',
      '--supply-color': '#E5D540',
      '--yours-table-title': '#E5D540',
      '--borrow-color': '#E69E40',
      '--withdraw-bg-color': '#E5D540',
      '--withdraw-border-color': '#E5D540',
      '--withdraw-bg-hover-color': 'rgba(229, 213, 64, 0.8)',
      '--repay-bg-color': '#E69E40',
      '--repay-border-color': '#E69E40',
      '--repay-bg-hover-color': 'rgba(230, 158, 64, 0.8)',
      '--claim-bg-hover-color': 'rgba(229, 213, 64, 0.4)',
      '--claim-bg-color': 'rgba(229, 213, 64, 0.2)',
      '--claim-border-color': 'rgba(229, 213, 64, 0.2)',
      '--withdraw-color': '#000',
      '--replay-color': '#000',
      '--claim-color': '#E5D540',
    },
  },
  liqee: {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
  'shoebill-v2': {
    type: 'lending',
    theme: {
      '--switch-color': '',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '',
      '--repay-border-color': '',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
  'gravita-protocol': {
    type: 'lending',
    theme: {
      '--switch-color': '#D079FF',
      '--button-text-color': '',
      '--supply-color': '',
      '--yours-table-title': '',
      '--borrow-color': '',
      '--withdraw-bg-color': '',
      '--withdraw-border-color': '',
      '--withdraw-bg-hover-color': '',
      '--repay-bg-color': '#D079FF',
      '--repay-border-color': '#D079FF',
      '--repay-bg-hover-color': '',
      '--claim-bg-hover-color': '',
      '--claim-bg-color': '',
      '--claim-border-color': '',
      '--withdraw-color': '',
      '--replay-color': '',
      '--claim-color': '',
    },
  },
};

export default ROUTE_CONFIG;
