const ROUTE_CONFIG = {
  'aura-finance': {
    type: 'staking',
    theme: {
      '--button-color': '#783ae3',
      '--switch-color': '#783ae3',
      '--button-text-color': '#FFFFFF',
      '--supply-color': '#783ae3',
      '--yours-table-title': '#FFFFFF',
      '--borrow-color': '#783ae3',
      '--withdraw-bg-color': '#783ae3',
      '--withdraw-border-color': '#783ae3',
      '--withdraw-bg-hover-color': '#783ae3',
      '--repay-bg-color': '#783ae3',
      '--repay-border-color': '#783ae3',
      '--repay-bg-hover-color': '#783ae3',
      '--claim-bg-hover-color': '#783ae3',
      '--claim-bg-color': '#783ae3',
      '--claim-border-color': '#783ae3',
      '--withdraw-color': '#783ae3',
      '--replay-color': '#783ae3',
      '--claim-color': '#783ae3',
    },
  },
  'athena-finance': {
    type: 'staking',
    theme: {
      '--button-color': '#1aca8a',
      '--switch-color': '#1aca8a',
      '--button-text-color': '#FFFFFF',
      '--supply-color': '#1aca8a',
      '--yours-table-title': '#FFFFFF',
      '--borrow-color': '#1aca8a',
      '--withdraw-bg-color': '#1aca8a',
      '--withdraw-border-color': '#1aca8a',
      '--withdraw-bg-hover-color': '#1aca8a',
      '--repay-bg-color': '#1aca8a',
      '--repay-border-color': '#1aca8a',
      '--repay-bg-hover-color': '#1aca8a',
      '--claim-bg-hover-color': '#1aca8a',
      '--claim-bg-color': '#1aca8a',
      '--claim-border-color': '#1aca8a',
      '--withdraw-color': '#1aca8a',
      '--replay-color': '#1aca8a',
      '--claim-color': '#1aca8a',
    },
  },
};

export default ROUTE_CONFIG;
