name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run code formatting check
        run: pnpm run prettier

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run lint check
        run: pnpm run build

