name: 'Issue States'

on:
  project_card:
    types: [created, edited, moved]

permissions:
  repository-projects: read
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/issue-states@v3
        with:
          github-token: ${{ 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 }}
          open-issue-columns: ''
          closed-issue-columns: 'Closed, Done'
          log-output: false
