name: Automatic Github Releases

on: 
  push:
    branches:
      - "main"

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Get current date
      id: name
      run: echo "::set-output name=date::$(date +'%m-%d-%Y')"
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1.14.0
      with:
        generateReleaseNotes: true
        tag: ${{ steps.name.output.name }}
        makeLatest: true
        allowUpdates: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}